spots = ["fuzikyu", "jukai", "shirakamisanti", "north pole", "yamanashi"]

print(spots)
print(sorted(spots))
print(spots)
print(sorted(spots, reverse = True))
print(spots)
spots.reverse()
print(spots)
spots.reverse()
print(spots)
spots.sort()
print(spots)
spots.sort(reverse=True)
print(spots)